### ISSUE TITLE
Readme.md contains links to non-existent devel.mathjax.org

### ISSUE THREAD

**Issue by HelioGuilherme66** [mathjax/MathJax-test#19]
In the "Installation and Usage" section we have:
"The documents are also available on the MathJax-test web site on line at http://devel.mathjax.org/testing/web/docs/html/ and http://devel.mathjax.org/testing/web/docs/doxygen/."

Clicking on those links (or with HTTPS) leads to "Server not found" errors.

**Comment by pkra** [comment]
Thanks for catching these. They don't exist anymore.

**Comment by pkra** [comment]
Fixed by https://github.com/mathjax/MathJax-test/commit/c4d40739d93a94e93d583cf4070dad4bcf514b9a
